export { default as Expo } from './expo.png';
export { default as JS } from './js.png';
export { default as Plotly } from './plotly.png';
export { default as Python } from './python.png';
export { default as R } from './r.png';
export { default as ReactLogo } from './react.png';
export { default as Shiny } from './shiny.png';
export { default as Ionic } from './ionic.png';
export { default as TS } from './ts.png';
